apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sporretime
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 3000
  liveness:
    path: /api/isAlive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /api/isReady
    initialDelay: 20
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /actuator/metrics
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
      replyURLs:
        - "https://sporretime.dev.intern.nav.no/oauth2/callback"
      claims:
        extra:
          - "NAVident"
  ingresses:
    - "https://sporretime.dev.intern.nav.no"
  accessPolicy:
    outbound:
      external:
        - host: sporsmalogsvar.dev.intern.nav.no
  env:
    - name: NAIS_CONTEXT
      value: 'dev'
    - name: NODE_ENV
      value: "production"
