import Head from 'next/head'
import styles from '@/src/styles/Home.module.css'
import {Button, TextField} from "@navikt/ds-react";
import {useState} from "react";

const texts = {
  header: "Spørretime",
  inputLabel: "ID",
  buttonText: "Klikk her!",
  getButtonText: "Klikk her for get!",
}

interface SessionDTO {
  code: string;
}

export default function Home() {
  const [id, setId] = useState<string>("");

  const submit = () => {
    if(id.length > 0) {
      const body: SessionDTO = {
        code: id,
      };

      fetch("/api/sporsmalogsvar/session", {
        method: "POST",
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(body),
      });
    }
  };

  const handleGetClick = () => {
    fetch("/api/sporsmalogsvar/sporsmal", {
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
    })
      .catch((error) => {
        console.log("Got error! :(");
      })
  }

  return (
    <>
      <Head>
        <title>Spørretime</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <div>
          <h1>{texts.header}</h1>
          <div className={styles.description}>
            <TextField label={texts.inputLabel} onChange={(event) => setId(event.target.value)}/>
            <Button onClick={submit}>
              {texts.buttonText}
            </Button>
          </div>
          <div>
            <Button onClick={handleGetClick}>
              {texts.getButtonText}
            </Button>
          </div>
        </div>
      </main>
    </>
  )
}
